CONFIG_SPI=y
CONFIG_SSD1306=y
CONFIG_SSD1306_DEFAULT_CONTRAST=128
CONFIG_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=y

# needed for the k_malloc function used by cfb library
CONFIG_HEAP_MEM_POOL_SIZE=16384

# compiler
CONFIG_DEBUG_OPTIMIZATIONS=y

#Zephyr boot banner
CONFIG_BOOT_BANNER=y
#CONFIG_BOOT_BANNER_STRING=""

# logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
#CONFIG_APP_LOG_LEVEL_DBG=y
#CONFIG_DISPLAY_LOG_LEVEL_DBG=y
#CONFIG_CFB_LOG_LEVEL_DBG=y
